export const jobsData = [
  {
    slug: 'senior-platform-engineer',
    title: 'Senior Platform Engineer',
    company: 'Northstar Health',
    location: 'Remote',
    type: 'Remote',
    salary: '$150,000–$210,000',
    department: 'Platform',
    summary: 'Own the platform roadmap for a modern health intelligence platform with a focus on stability, performance, and developer velocity.',
    match: 96,
    applicants: 48,
    posted: '2 days ago',
  },
  {
    slug: 'cloud-infrastructure-lead',
    title: 'Cloud Infrastructure Lead',
    company: 'SummitGrid',
    location: 'Austin, TX',
    type: 'Hybrid',
    salary: '$140,000–$195,000',
    department: 'Cloud',
    summary: 'Lead migration and modernization initiatives across an enterprise AWS environment powering high-scale digital infrastructure.',
    match: 92,
    applicants: 36,
    posted: '1 day ago',
  },
  {
    slug: 'ai-systems-engineer',
    title: 'AI Systems Engineer',
    company: 'Aegis Labs',
    location: 'Remote',
    type: 'Remote',
    salary: '$165,000–$230,000',
    department: 'AI',
    summary: 'Design ML systems and deployment workflows for applied AI products spanning data services, automation, and analytics.',
    match: 98,
    applicants: 57,
    posted: '3 days ago',
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    company: 'VerveOps',
    location: 'Denver, CO',
    type: 'On-site',
    salary: '$120,000–$180,000',
    department: 'Security',
    summary: 'Protect the product and infrastructure stack with a focus on incident response, posture management, and tooling.',
    match: 88,
    applicants: 29,
    posted: '4 hours ago',
  },
  {
    slug: 'product-designer',
    title: 'Product Designer',
    company: 'LaunchPeak',
    location: 'New York, NY',
    type: 'Hybrid',
    salary: '$95,000–$160,000',
    department: 'Design',
    summary: 'Shape customer experience and platform strategy for enterprise SaaS products with a strong design systems mindset.',
    match: 90,
    applicants: 33,
    posted: '5 days ago',
  },
  {
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    company: 'Crestline',
    location: 'Remote',
    type: 'Remote',
    salary: '$105,000–$175,000',
    department: 'DevOps',
    summary: 'Build resilient CI/CD, observability, and infrastructure automation for regulated and high-scale applications.',
    match: 94,
    applicants: 41,
    posted: '6 hours ago',
  },
];

export const metricsList = [
  { label: 'Open roles', value: '48', detail: '+14% this quarter' },
  { label: 'Qualified candidates', value: '1,286', detail: 'Across 22 disciplines' },
  { label: 'Time to hire', value: '12 days', detail: '2.4x faster than market' },
  { label: 'Client satisfaction', value: '98%', detail: 'Average satisfaction score' },
];

export const candidateMetrics = [
  { label: 'Profile strength', value: '92%', detail: 'AI profile score' },
  { label: 'Applications sent', value: '18', detail: 'This month' },
  { label: 'Interviews booked', value: '6', detail: '2 moving forward' },
  { label: 'Saved roles', value: '12', detail: 'High-priority list' },
];
